name: API Automation Framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 45 20 * * *
    - cron: 55 20 * * *
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Execute tests
      run: mvn clean test -Dsuite=suite_Smoke -X

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
       name: logs
       path: logs/

    
